/*
 * This file has been generated by flow2code
 * See: https://flow.liwe.org
 */

import { ILRequest, ILResponse, ILError, ILiWE } from '../../liwe/types';
import { send_error, send_ok, typed_dict } from "../../liwe/utils";
import { locale_load } from '../../liwe/locale';

import { perms } from '../../liwe/auth';
import { LiWEResponse, sendParametersError, sendResponse } from '../../liwe/response';

import {
	// endpoints function
	delete_session_admin_del, get_session_admin_list, get_session_me,
	// functions
	session_create, session_db_init, session_del, session_get, session_id,
	session_remove_all, session_set_val,
} from './methods';

import {
	Session, SessionData, SessionDataKeys, SessionKeys,
} from './types';

/*=== f2c_start __header ===*/

/*=== f2c_end __header ===*/

export const init = ( liwe: ILiWE ) => {
	const app = liwe.app;

	console.log( "    - session " );

	liwe.cfg.app.languages.map( ( l ) => locale_load( "session", l ) );
	session_db_init ( liwe );

	app.get ( '/api/session/admin/list', perms( [ "session.manage" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { domain, ___errors } = typed_dict( req.query as any, [
			{ name: "domain", type: "string" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await get_session_admin_list ( req, domain);
		sendResponse ( res, response );
	} );

	app.delete ( '/api/session/admin/del', perms( [ "session.manage" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { key, ___errors } = typed_dict( req.body, [
			{ name: "key", type: "string", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await delete_session_admin_del ( req, key);
		sendResponse ( res, response );
	} );

	app.get ( '/api/session/me', perms( [ "is-logged" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		

		const response = await get_session_me ( req, );
		sendResponse ( res, response );
	} );

};
