/*
 * This file has been generated by flow2code
 * See: https://flow.liwe.org
 */

import { ILRequest, ILResponse, LCback, ILiweConfig, ILError, ILiWE } from '../../liwe/types';
import { LiWEError, LiWEResponse, responseError, responseSuccess } from '../../liwe/response';
import { $l } from '../../liwe/locale';
import { system_permissions_register } from '../system/methods';

import {
	Session, SessionData, SessionDataKeys, SessionKeys,
} from './types';

import _module_perms from './perms';

let _liwe: ILiWE = null;

const _ = ( txt: string, vals: any = null, plural = false ) => {
	return $l( txt, vals, plural, "session" );
};

const COLL_SESSIONS = "sessions";

/*=== f2c_start __file_header === */
import { get_real_ip } from '../../liwe/defender';
import { md5 } from '../../liwe/utils';
import { adb_query_one, adb_record_add, adb_find_one, adb_find_all, adb_query_all, adb_prepare_filters, adb_collection_init, adb_del_one, adb_del_all } from '../../liwe/db/arango';

const _session_key = ( req: ILRequest, session_id: string ) => {
	console.log( "SESSION KEY - REAL IP: ", get_real_ip( req ), session_id );
	const _ip = req.cfg.security.session?.bind_ip ? get_real_ip( req ) : req.cfg.security.secret;

	return session_id + "-" + md5( `${ session_id }-${ _ip }` );
};
/*=== f2c_end __file_header ===*/

// {{{ get_session_admin_list ( req: ILRequest, domain?: stringcback: LCBack = null ): Promise<Session[]>
/**
 *
 * The call returns a list of all available tag.
 * If `domain` is specified, only sessions belonging to that domain will be returned.
 *
 * @param domain - The domain, if not set the session domain will be used [opt]
 *
 * @return sessions: Session
 *
 */
export const get_session_admin_list = async ( req: ILRequest, domain?: string ): Promise<LiWEResponse<Session[]>> => {
	/*=== f2c_start get_session_admin_list ===*/
	const [ filters, values ] = adb_prepare_filters( 'session', { domain } );
	const sessions: Session[] = await adb_query_all( req.db, `FOR session IN ${ COLL_SESSIONS } ${ filters } RETURN session`, values );

	return responseSuccess( sessions );
	/*=== f2c_end get_session_admin_list ===*/
};
// }}}

// {{{ delete_session_admin_del ( req: ILRequest, key: stringcback: LCBack = null ): Promise<boolean>
/**
 *
 * Deletes a session from the system.
 *
 * @param key - The session `key` [req]
 *
 * @return ok: boolean
 *
 */
export const delete_session_admin_del = async ( req: ILRequest, key: string ): Promise<LiWEResponse<boolean>> => {
	/*=== f2c_start delete_session_admin_del ===*/
	await adb_del_one( req.db, COLL_SESSIONS, { key } );

	return responseSuccess( true );
	/*=== f2c_end delete_session_admin_del ===*/
};
// }}}

// {{{ get_session_me ( req: ILRequest, cback: LCBack = null ): Promise<Session>
/**
 *
 * Returns the current user session.
 *
 *
 * @return session: Session
 *
 */
export const get_session_me = async ( req: ILRequest, ): Promise<LiWEResponse<Session>> => {
	/*=== f2c_start get_session_me ===*/
	const sess: Session = await session_get( req, req.user.session_key );
	return responseSuccess( sess );
	/*=== f2c_end get_session_me ===*/
};
// }}}

// {{{ session_set_val ( req: ILRequest, key: string, val: string, cback: LCBack = null ): Promise<any>
/**
 *
 * This function sets a new value inside the current session.
 * If the session is expired or does not exists, an empty object is returned.
 *
 * @param req - The ILRequest [req]
 * @param key - The key to set in the session [req]
 * @param val - The value to be set in the session [req]
 *
 * @return : any
 *
 */
export const session_set_val = async ( req: ILRequest, key: string, val: string, ): Promise<any> => {
	/*=== f2c_start session_set_val ===*/
	let sess = await session_get( req, ( req.user as any ).session_key, true );

	sess.data[ key ] = val;

	sess = await adb_record_add( req.db, COLL_SESSIONS, sess, SessionKeys );

	return responseSuccess( sess );
	/*=== f2c_end session_set_val ===*/
};
// }}}

// {{{ session_id ( req: ILRequest, id_user: string = "null", cback: LCBack = null ): Promise<string[]>
/**
 *
 * Returns the session_id of the current user
 *
 * @param req - The ILRequest [req]
 * @param id_user - The *forced* id user [opt]
 *
 * @return : string
 *
 */
export const session_id = async ( req: ILRequest, id_user: string = "null", ): Promise<string[]> => {
	/*=== f2c_start session_id ===*/
	if ( !id_user ) id_user = req.user?.id;
	const _session_id = md5( id_user );

	return [ _session_key( req, _session_id ), _session_id ];
	/*=== f2c_end session_id ===*/
};
// }}}

// {{{ session_remove_all ( req: ILRequest, session_id: string, cback: LCBack = null ): Promise<boolean>
/**
 *
 * Remove all the session related to current `session_id`.
 *
 * @param req - The ILRequest [req]
 * @param session_id - The session id [req]
 *
 * @return : boolean
 *
 */
export const session_remove_all = async ( req: ILRequest, session_id: string, ): Promise<boolean> => {
	/*=== f2c_start session_remove_all ===*/
	await adb_del_all( req.db, COLL_SESSIONS, { key: session_id } );

	return true;
	/*=== f2c_end session_remove_all ===*/
};
// }}}

// {{{ session_del ( req: ILRequest, session_key: string, cback: LCBack = null ): Promise<boolean>
/**
 *
 * Removes a session from the system.
 *
 * @param req - The ILRequest [req]
 * @param session_key - The Session key [req]
 *
 * @return : boolean
 *
 */
export const session_del = async ( req: ILRequest, session_key: string, ): Promise<boolean> => {
	/*=== f2c_start session_del ===*/
	await adb_del_all( req.db, COLL_SESSIONS, { key: session_key } );

	return true;
	/*=== f2c_end session_del ===*/
};
// }}}

// {{{ session_get ( req: ILRequest, session_key: string, full: boolean = false, cback: LCBack = null ): Promise<any>
/**
 *
 * This function retrieves the session from the sessions collection, using the JWT token provided.
 * If the session is expired or does not exists, an empty object is returned.
 *
 * @param req - The ILRequest [req]
 * @param session_key - The session unique key [req]
 * @param full - If the session should return all info and not just data [opt]
 *
 * @return : any
 *
 */
export const session_get = async ( req: ILRequest, session_key: string, full: boolean = false, ): Promise<any> => {
	/*=== f2c_start session_get ===*/
	const res = await adb_query_one( req.db, "FOR u IN sessions FILTER u.key == @key RETURN u", { key: session_key } );

	if ( !res ) return null;

	if ( full ) return res;

	return res.data;
	/*=== f2c_end session_get ===*/
};
// }}}

// {{{ session_create ( req: ILRequest, session_key: string, domain: string, data: any, cback: LCBack = null ): Promise<any>
/**
 *
 * This function retrieves the session from the sessions collection, using the JWT token provided.
 * If the session is expired or does not exists, an empty object is returned.
 *
 * @param req - The ILRequest [req]
 * @param session_key - The session unique key [req]
 * @param domain - The domain name [req]
 * @param data - The initial data to be saved [req]
 *
 * @return : any
 *
 */
export const session_create = async ( req: ILRequest, session_key: string, domain: string, data: any, ): Promise<any> => {
	/*=== f2c_start session_create ===*/
	await session_del( req, session_key );

	await adb_record_add( req.db, COLL_SESSIONS, { key: session_key, domain, data } );

	return responseSuccess( true );
	/*=== f2c_end session_create ===*/
};
// }}}

// {{{ session_db_init ( liwe: ILiWE, cback: LCBack = null ): Promise<boolean>
/**
 *
 * Initializes the module's database
 *
 * @param liwe - The Liwe object [req]
 *
 * @return : boolean
 *
 */
export const session_db_init = async ( liwe: ILiWE, ): Promise<boolean> => {
	_liwe = liwe;

	system_permissions_register( 'session', _module_perms );

	await adb_collection_init( liwe.db, COLL_SESSIONS, [
		{ type: "persistent", fields: [ "key" ], unique: true },
		{ type: "persistent", fields: [ "domain" ], unique: false },
	], { drop: false } );

	/*=== f2c_start session_db_init ===*/

	/*=== f2c_end session_db_init ===*/

	return true;
};
// }}}


